# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Virtualbox
        run: |
          sudo apt-get update
          sudo apt-get install virtualbox

      - name: Install Vagrant
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vagrant
          vagrant --version

      - name: Start a vagrant
        run: |
          vagrant init hashicorp/bionic64
          # Save me the heredoc!
          cat Vagrantfile
          vagrant up

      # Runs series of commands inside guest, demonstrating they are sequenced with cd.
      - name: Run series of commands inside guest
        run: |
          vagrant ssh -- -t "uname -a; lsb_release -a; ip a; whoami; free -h; df -h; pwd; cd /; pwd; top -n2"
